#!/bin/bash

# finds rigctl and rotctl PIDs and SIGTERMs them
# Michael Hirsch

RigPID=$(pgrep rigctld)
RotPID=$(pgrep rotctld)

[[ -n $RigPID ]] && { echo "Stopping rigctld PID $RigPID"; kill $RigPID; }

[[ -n $RotPID ]] && { echo "Stopping rotctld PID $RotPID"; kill $RotPID; }
